Get polluted location from API
vu-vibedosa/apsitvarkom-fe pull request #18
Opened 2022-10-06 07:27 UTC by 6ar8nas

## What was done

- Deleted PollutedLocationType
- Adjusted the type that is returned by getAllPollutedLocations
- Implemented using data from API

The title is currently hardcoded in the PollutedLocationCard. That will need to be adjusted.

2022-10-06 18:52 UTC, BaVilius requested changes
LGTM, if You don't agree with my naming suggestions, let me know why 😄

2022-10-06 18:52 UTC, BaVilius commented on src/App.tsx
> +          response.data.map((loc) => mapToPollutedLocation(loc))
It's a bit of nitpick, but I think we shouldn't shorten variables names for the sake of better readability. Here I would change `loc` to `location`.

2022-10-06 18:52 UTC, BaVilius commented on src/App.tsx
> +        {pollutedLocations.map((pl) => (
Same here with `pl`.

2022-10-07 05:43 UTC, BaVilius approved these changes
Great, I think You can merge.

2022-10-07 07:21 UTC, BenasB approved these changes
LGTM, although we'll probably want to add some loading/success/error conditional rendering in the future. Feel free to merge when you can

2022-10-07 09:05 UTC, merged